version: '3.9'
services:
  web:
    build: ./docker/nginx
    container_name: ${PROJECT_NAME}-nginx
    ports:
      - 8080:80
      - 8443:443
    restart: always
    links: 
      - php-fpm
    volumes:
      - ./html:/usr/share/nginx/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  php-fpm:
    build: ./docker/php
    container_name: ${PROJECT_NAME}-php
    ports:
      - 9000:9000
    volumes:
      - ./html:/usr/share/nginx/html
networks:
  develop-networks: